name: aicamera
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  camera: ^0.9.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.3
  get: 4.3.8
  hexcolor: ^2.0.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
